"""v17 deterministic flow model — MSE regression of null-space velocity.

Predicts v_θ(q, t_norm, c) → R^7 directly. Trained with MSE on ground-truth
v* extracted from dataset trajectories (3D J_pos null-space projection).

Why MSE over CFM here: this dataset is generated by ONE deterministic
controller, so v* | (q, t, c) is essentially a delta. MSE learns the
delta efficiently; CFM's stochastic interpolation adds ODE-integration
noise that hurts on deterministic data. CFM becomes useful when the
training data is multimodal (multiple controllers, real-robot noise,
human demos, etc.) — to be revisited when dataset is expanded.

Inputs:
  q      (B, 7)   current joint state
  t_norm (B,)     normalized progress along path, ∈ [0, 1]
  c      (B, 9)   task context [direction(3), plane_normal(3), plane_point(3)]

Output:
  v_θ    (B, 7)   predicted null-space velocity (will be projected via P at deploy)
"""
from __future__ import annotations
import torch
import torch.nn as nn


class FlowModel(nn.Module):
    def __init__(self, q_dim: int = 7, c_dim: int = 9, hidden: int = 256,
                 depth: int = 4):
        super().__init__()
        in_dim = q_dim + 1 + c_dim                       # +1 for t_norm
        layers = [nn.Linear(in_dim, hidden), nn.SiLU()]
        for _ in range(depth - 2):
            layers += [nn.Linear(hidden, hidden), nn.SiLU()]
        layers += [nn.Linear(hidden, q_dim)]
        self.net = nn.Sequential(*layers)

    def forward(self, q: torch.Tensor, t_norm: torch.Tensor,
                c: torch.Tensor) -> torch.Tensor:
        if t_norm.ndim == 1:
            t_norm = t_norm.unsqueeze(-1)
        x = torch.cat([q, t_norm, c], dim=-1)
        return self.net(x)


def damped_pinv(J: torch.Tensor, lam: float = 0.01) -> torch.Tensor:
    """J: (..., R, 7) → J†: (..., 7, R).  Levenberg-Marquardt damping."""
    sh = J.shape
    R = sh[-2]
    eyeR = torch.eye(R, device=J.device, dtype=J.dtype).expand(*sh[:-2], R, R)
    JJT = J @ J.transpose(-1, -2) + (lam ** 2) * eyeR
    return J.transpose(-1, -2) @ torch.linalg.inv(JJT)


def null_projector(J: torch.Tensor, lam: float = 0.01) -> torch.Tensor:
    """Returns I_7 - J† J  for null-space projection."""
    sh = J.shape
    Jd = damped_pinv(J, lam=lam)
    eye7 = torch.eye(7, device=J.device, dtype=J.dtype).expand(*sh[:-2], 7, 7)
    return eye7 - Jd @ J


def damped_pinv(J: torch.Tensor, lam: float = 0.01) -> torch.Tensor:
    """J: (..., 6, 7) → J†: (..., 7, 6).  Levenberg-Marquardt damping."""
    sh = J.shape
    eye6 = torch.eye(6, device=J.device, dtype=J.dtype).expand(*sh[:-2], 6, 6)
    JJT = J @ J.transpose(-1, -2) + (lam ** 2) * eye6
    return J.transpose(-1, -2) @ torch.linalg.inv(JJT)


def null_projector(J: torch.Tensor, lam: float = 0.01) -> torch.Tensor:
    """Returns I_7 - J† J  for null-space projection."""
    sh = J.shape                                          # (..., 6, 7)
    Jd = damped_pinv(J, lam=lam)                          # (..., 7, 6)
    eye7 = torch.eye(7, device=J.device, dtype=J.dtype).expand(*sh[:-2], 7, 7)
    return eye7 - Jd @ J
